### ISSUE TITLE
add a good font to the overall website

### ISSUE THREAD

**Issue by ShravaniAK** [ShravaniAK/noter-js#13]

**Comment by muneeb-i-khan** [comment]
Assign this to me @ShravaniAK

**Comment by ChaudharyRaman** [comment]
Hi @ShravaniAK . I would like to contribute to this issue. Assign it to me.

**Comment by Paari1263** [comment]
Can you assign me @ShravaniAK

**Comment by Ayush-Khandelwal28** [comment]
I would like to contribute, can you assign it to me @ShravaniAK
