### ISSUE TITLE
improve the ui

### ISSUE THREAD

**Issue by ShravaniAK** [ShravaniAK/noter-js#2]

**Comment by CDPhu** [comment]
Hello [ShravaniAK](https://github.com/ShravaniAK), I would like to be assigned this for Hacktoberfest 2022, thank you.

**Comment by kanisshka** [comment]
i want to work on this issue

**Comment by CDPhu** [comment]
@ShravaniAK , any particular color theme? I was thinking purple.

**Comment by kanisshka** [comment]
> @ShravaniAK , any particular color theme? I was thinking purple.

no i'm not thinking of any particular color theme
