### ISSUE TITLE
improve search input and button

### ISSUE THREAD

**Issue by Abhirv08** [ShravaniAK/noter-js#21]
Upon opening the site, the Search bar was broken down,
Assign it to me so that I can fix this issue.
![Screenshot 2022-10-01 100130](https://user-images.githubusercontent.com/81900610/193392702-b14ed103-c544-46a4-bde8-4fd17de05022.png)

**Comment by deven-533** [comment]
Hello Sir ,I would Like to fix this issue , Please Assign it To me
