### ISSUE TITLE
improve Add Note button

### ISSUE THREAD

**Issue by Abhirv08** [ShravaniAK/noter-js#28]
The Add Note button is not looking good as Add and Note are coming in two different lines.
Also, copyright text is not looking good on the left, either aligning it to the center will be good or removing it.

Assign me to fix it.

**Comment by Aman1143** [comment]
I want to solve this bug. can you allow me ??

**Comment by Aman1143** [comment]
I think after hovering on Add Note button ,it does not change any transion like color etc. if we add feature on it . then it definatly looks awesome . and in this repo there is no copyright section. if we add it . then definatly increase the dashboard looks.
i want to contribute in this repo. can you allow me to do the above part.
