### ISSUE TITLE
add error message when submitting blank notes.

### ISSUE THREAD

**Issue by ShravaniAK** [ShravaniAK/noter-js#34]

**Comment by aatharvauti** [comment]
Hey there! I would like to contribute and solve this issue.

**Comment by muneeb-i-khan** [comment]
Hey I would like to  work on this

**Comment by muneeb-i-khan** [comment]
Hey @ShravaniAK , I've solved this issue. You can check if everything is all good.

**Comment by pantheism2709** [comment]
Hey Mam, I want to work on this task, Please assign it to me @ShravaniAK
