### ISSUE TITLE
write js for adding the notes 

### ISSUE THREAD

**Issue by ShravaniAK** [ShravaniAK/noter-js#42]

**Comment by nalin243** [comment]
Could you assign this to me? I can give it a try

**Comment by nalin243** [comment]
The js is already written, there was a typo in the js file which i fixed. Could you assign this to me?

**Comment by ShravaniAK** [comment]
are you working on the issue @nalin243

**Comment by nalin243** [comment]
I created a pull request for the typo fix and it has been merged. The add notes functionality  is back on the live app @ShravaniAK
