### ISSUE TITLE
Bug in note deletion

### ISSUE THREAD

**Issue by nalin243** [ShravaniAK/noter-js#61]
Wrong usage of splice method

**Comment by ShravaniAK** [comment]
can you please add ss and elobrate the issue

**Comment by nalin243** [comment]
The line noteObj.splice(index,index) was deleting multiple notes as once as the syntax for splice is that we have to give the index to be deleted, along with the number of items deleted at that index. 

To reproduce it just create 6 notes and delete the fourth one, sixth and fifth also get deleted.

noteObj(index,1) fixes that @ShravaniAK
