### ISSUE TITLE
improve the ui of the card

### ISSUE THREAD

**Issue by ShravaniAK** [ShravaniAK/noter-js#8]

**Comment by ChaudharyRaman** [comment]
hii @ShravaniAK . i would like to work on this issue. can you please assign it to me?

**Comment by kataranandini** [comment]
I would also like to work on it please assign it to me

**Comment by kanisshka** [comment]
i want to work on this issue

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.
